// all the libraries of all the modules in the project

object Versions {
    const val gradle_version = "3.6.1"
    const val gradle_bintray_plugin = "1.8.4"
    const val android_maven_gradle_plugin = "2.1"
    const val kotlin_stdlib = "1.3.72"
    const val kotlin_gradle_plugin = "1.3.72"
    const val junit = "4.12"
    const val appcompat = "1.2.0"
    const val constraintlayout = "2.0.4"
    const val recyclerview = "1.1.0"
    const val retrolambda = "3.6.0"
    const val cardview = "1.0.0"
    const val rxjava = "2.1.16"
    const val rxandroid = "2.0.1"
    const val text_junit = "1.1.2"
    const val espresso_core = "3.3.0"
    const val palette_ktx = "1.0.0"
    const val material = "1.3.0-alpha04"
    const val arouter_api = "1.5.0"
    const val arouter_compiler = "1.2.2"
    const val glide = "3.8.0"
    const val okhttp_integration = "1.3.1"
    const val fresco = "0.12.0"
    const val animated_gif = "0.12.0"
    const val animated_webp = "0.12.0"
    const val webpsupport = "0.12.0"
    const val rxpermissions = "0.9.4@aar"
    const val guava = "29.0-jre"
    const val multidex = "2.0.1"
    const val text_runner = "1.3.0"
}

object Libs {
    val gradle_version = "com.android.tools.build:gradle:${Versions.gradle_version}"
    val gradle_bintray_plugin = "com.jfrog.bintray.gradle:gradle-bintray-plugin:${Versions.gradle_bintray_plugin}"
    val android_maven_gradle_plugin = "com.github.dcendents:android-maven-gradle-plugin:${Versions.android_maven_gradle_plugin}"
    val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin_stdlib}"
    val kotlin_gradle_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin_gradle_plugin}"
    val junit = "junit:junit:${Versions.junit}"
    val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    val constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintlayout}"
    val recyclerview = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    val retrolambda = "me.tatarka:gradle-retrolambda:${Versions.retrolambda}"
    val cardview = "androidx.cardview:cardview:${Versions.cardview}"
    val rxjava = "io.reactivex.rxjava2:rxjava:${Versions.rxjava}"
    val rxandroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    val text_junit = "androidx.test.ext:junit:${Versions.text_junit}"
    val espresso_core = "androidx.test.espresso:espresso-core:${Versions.espresso_core}"
    val palette_ktx = "androidx.palette:palette-ktx:${Versions.palette_ktx}"
    val material = "com.google.android.material:material:${Versions.material}"
    val arouter_api = "com.alibaba:arouter-api:${Versions.arouter_api}"
    val arouter_compiler = "com.alibaba:arouter-compiler:${Versions.arouter_compiler}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val okhttp_integration = "com.github.bumptech.glide:okhttp-integration:${Versions.okhttp_integration}"
    val fresco = "com.facebook.fresco:fresco:${Versions.fresco}"
    val animated_gif = "com.facebook.fresco:animated-gif:${Versions.animated_gif}"
    val animated_webp = "com.facebook.fresco:animated-webp:${Versions.animated_webp}"
    val webpsupport = "com.facebook.fresco:webpsupport:${Versions.webpsupport}"
    val rxpermissions = "com.tbruyelle.rxpermissions2:rxpermissions:${Versions.rxpermissions}"
    val guava = "com.google.guava:guava:${Versions.guava}"
    val multidex = "androidx.multidex:multidex:${Versions.multidex}"
    val text_runner = "androidx.test:runner:${Versions.text_runner}"
}